version = 1

[[annotations]]
path = ["src/resources/icons/**/*.svg", "**/*.png", "**/*.svg", "**/*.ico"]
SPDX-FileCopyrightText = "www.svgrepo.com"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["flake.lock"]
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["src/data/org.kde.drawy.desktop", "src/data/org.kde.drawy.metainfo.xml", ".gersemirc"]
SPDX-FileCopyrightText = "Prayag Jain <prayagjain2@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"
